version: "3.8"

services:
  db:
    build:
      context: ./database/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: musicdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d musicdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      REDIS_URL: "redis://redis:6379"
      DATABASE_URL: "postgresql://admin:admin@db:5432/musicdb"
      USER_CACHE_TTL: 7200
      SESSION_CACHE_TTL: 3600
      VERIFY_TTL: 1800
      VERIFY_ATTEMPTS: 3
      EMAIL_USER: david.ter.1889@gmail.com
      EMAIL_PASSWORD: ntumeooqmmfeyrqe
      JWT_SECRET: AsdasdasdasDsd123123123
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
