events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server auth:3000;
    }

    upstream soundcloud_service {
        server soundcloud:3000;
    }

    upstream library_service {
        server library:3000;
    }

    server {
        listen 80;

        # Auth Service
        location /api/auth/ {
            rewrite ^/api/auth/(.*) /$1 break;
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # SoundCloud Service
        location /api/soundcloud/ {
            rewrite ^/api/soundcloud/(.*) /$1 break;
            proxy_pass http://soundcloud_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Library Service
        location /api/library/ {
            rewrite ^/api/library/(.*) /$1 break;
            proxy_pass http://library_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
